### PR TITLE
init pbr

### PR DESCRIPTION
**Pull request by alpcihan**

### CODE REVIEW

**Comment by alpcihan** [comment]
[PBR](https://trello.com/c/lSOTSjV5/6-pbr)

**Review by umuterc — COMMENTED** [review]
Is the sharp changes on the diffuse lighting expected behaviour ? 
image

**Comment by alpcihan** [comment]
> Is the sharp changes on the diffuse lighting expected behaviour ? image

yes

**Comment by alpcihan** [comment]
> Is the sharp changes on the diffuse lighting expected behaviour ? image
> 
> yes (as a starting point). here is a screenshot from Unity URP as a reference: Capture

yes (as a starting point). here is a screenshot from Unity URP as a reference:
Capture

**Comment by alpcihan** [comment]
> Is the sharp changes on the diffuse lighting expected behaviour ? image

yes (as a starting point), it makes sense mathematically. Also used Unity URP as a reference:
Capture

**Pull request merged**
